Flask-Pika app
appsignal/test-setups pull request #212
Opened 2024-06-18 11:50 UTC by luismiramirez

Add test setup for Flask + Pika. The consumer works as an independent worker.

Part of https://github.com/appsignal/appsignal-python/issues/181

2024-06-18 13:05 UTC, tombruijn requested changes

2024-06-18 13:05 UTC, tombruijn commented on python/flask-pika/app/app.py
> +        <li><a href="/custom"><kbd>/custom</kbd> &rarr; Use sample data helpers (send a POST request with JSON for params!)</a></li>
```suggestion
```
We don't need to repeat this for every flask derived app.

2024-06-18 13:05 UTC, tombruijn commented on python/flask-pika/app/app.py
> +    return "<p>Sent custom endpoint data!</p>"
```suggestion
```

This will also require some clean up on the imports.

2024-06-18 13:05 UTC, tombruijn commented on python/flask-pika/app/app.py
> +def publish_rabbit():
Plese add this route to the list of links on the index page.

2024-06-18 14:06 UTC, tombruijn approved these changes

2024-06-25 08:01 UTC, unflxw approved these changes

2024-06-26 10:01 UTC, merged